[package]
name = "lumio-voxel-project"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = []
spatial = []
mesh-collision = []

[dependencies]
lumio-voxel-contracts = { path = "../lumio-voxel-contracts" }
lumio-voxel-domain = { path = "../lumio-voxel-domain" }
lumio-voxel-ops = { path = "../lumio-voxel-ops" }
